name: CI

env:
  JAVA_VERSION: "21"
  JAVA_DISTRIBUTION: "temurin"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit messages
        uses: GsActions/commit-message-checker@v2
        with:
          pattern: "^(?!WIP).*$"
          error: "The first line cannot start with WIP"
          excludeDescription: "true"
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build & test with Gradle
        run: ./gradlew allTest

  publish:
    runs-on: ubuntu-latest
    needs: test
# TODO: Run only on the main branch
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to GitHub Packages
        run: ./gradlew publish -PconfigurePublishing=true
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
