name: CI

env:
  JAVA_VERSION: "21"
  JAVA_DISTRIBUTION: "temurin"

on:
  push:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_ID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to Maven Central (:gradle-core-api-utils)
        working-directory: ./kmpx-gradle-api-utils
        run: ./gradlew :gradle-core-api-utils:publishToMavenCentral --no-configuration-cache

      - name: Publish to Maven Central (:gradle-kotlin-api-utils)
        working-directory: ./kmpx-gradle-api-utils
        run: ./gradlew :gradle-kotlin-api-utils:publishToMavenCentral --no-configuration-cache

      - name: Publish to Maven Central (:collections)
        working-directory: ./kmpx-libraries
        run: ./gradlew :collections:publishToMavenCentral --no-configuration-cache

      - name: Publish to Maven Central (:js-api-compat)
        working-directory: ./kmpx-libraries
        run: ./gradlew :js-api-compat:publishToMavenCentral --no-configuration-cache

      - name: Publish to Maven Central (:platform)
        working-directory: ./kmpx-libraries
        run: ./gradlew :platform:publishToMavenCentral --no-configuration-cache
